### ISSUE TITLE
Findings LEDs

### ISSUE THREAD

**Issue by danko79** [codmpm/a1200-led-pcb#1]
Hi,i love this project but hard to find a array led can you help me?

**Comment by codmpm** [comment]
Hey, thank you. 
Sadly not. The board is intended as a PCB replacement using the original LED's. Maybe you can get a broken one somewhere and transplant the LED's?

Cheers,
Patrik

**Comment by danko79** [comment]
Ok,i understand was looking a board with a customize led's. 
Thanks
